#!/bin/bash
cols="$(tput cols)"
first=$(($cols/3))
second=$(($cols-$first))
lines="$(tput lines)"
i=0

for((c=0; c<$lines; c++)); do
    printf '\e[42;5;196m'
    for((i=0; i<$first; i++)); do
        printf ' '
        printf '\e[42;5;196m'
    done
    for((i=$first; i<$second; i++)); do
        printf ' '
        printf '\e[47;5;196m'
    done
    for((i=$second+1; i<=$cols; i++)); do
        printf ' '
        printf '\e[41;5;196m'
    done
    echo -e "\e[0m"
done
