---
  access_key_id: AKIAIUCPGWZ3NYI2IEIA
  secret_access_key: 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
  # Name of SSH key pair to use (available on AWS)
  key_pair: qwikLABS-L265-677806
  image_id: ami-d732f0b7
  instance_type: t2.micro
  availability-zone: us-west-2a
  security_group_ids: ["launch-wizard-1"]
